config/routes.rb
Rails.application.routes.draw do

  get 'management/index', as: "management"

  get 'special_offers/index', as: "special_offers"
  get 'special_offers/show/:id', to:"special_offers#show", as: "special_offer"
  get 'mini_special_offers/index', as: "mini_special_offers"
  get 'mini_special_offers/show/:id', to:"mini_special_offers#show", as: "mini_special_offer"

  namespace :admin do
    get 'deposit_types/show'
  end

  namespace :admin do
    get 'deposit_types/edit'
  end

  namespace :admin do
    get '/news', to:"news#index", as: "newsitems"
    get '/news/new', to:"news#new", as: "newsitem_new"
    post '/news', to:"news#create", as: "newsitem_create" 
    get '/news/:id', to:"news#show", as: "newsitem_show"
    get '/news/:id/edit', to:"news#edit", as: "newsitem_edit"
    patch '/news/:id', to:"news#update", as: "newsitem_update"
    delete '/news/:id', to:"news#delete", as: "newsitem_delete"
    
    post '/garants/add_image', to:"garants#add_image", as: "garant_images"
    post '/garants/add_detail', to:"garants#add_detail", as: "garant_details"
    post '/garants/destroy_image/:id/:image_id', to:"garants#destroy_image", as: "destroy_garant_image"
    post '/garants/destroy_detail/:id/:detail_id', to:"garants#destroy_detail", as: "destroy_garant_detail"
    resources :cash_terminals
    resources :garants
    resources :deposit_types
    resources :credit_types
    resources :credit_types
    resources :special_offers
    resources :mini_special_offers
    resources :offices
    resources :managers
    root "offices#index"

  end

  get 'garant/index', as: "garants"
  get 'garant/:garantid', to: "garant#show", as: "garant_show"

  get 'posterminals/index', as: "posterminals"

  get 'cards/index', as: "cards"

  get 'internetbank/index', as: "internetbank"

  get 'corraccounts/index', as: "corraccounts"

  get 'bankdetails/index', as: "bankdetails" 

  get 'report/index', as: "reports"

  get 'office/index', as: "offices"

  post 'office/show', as: "show_office_info"

  resources :users 
  
  post 'users/custom'

  namespace :products do
    namespace :credit_types do
      get 'credits(/:client_type(/:type_id))', to: "credits#index", defaults: {client_type: 1, type_id: 1}, as: "credits"
      get 'credits(/:client_type(/:type_id))/:product_id', to: "credits#show", defaults: {product_id: -1}, as: "creditdetails"
      post 'credits(/:client_type(/:type_id))/:product_id/calculate_rate_payment', to: "credits#calculate_rate_payment", defaults: {product_id: -1}, as: "calculate_rate_payment"
    end

    namespace :deposit_types do
      get 'deposits(/:client_type(/:type_id))', to: "deposits#index", defaults: {client_type: 1, type_id: 1}, as: "deposits"
      get 'deposits(/:client_type(/:type_id))/:product_id', to: "deposits#show", defaults: {product_id: -1}, as: "depositdetails"
      post 'deposits(/:client_type(/:type_id))/:product_id/calculate_rate_payment', to: "deposits#calculate_rate_payment", defaults: {product_id: -1}, as: "calculate_rate_payment"
    end

    namespace :transfer_types do 
      get '(:client_type)/international_transfers/', to: "international_transfers#index", defaults: {client_type: 1}, as: "international_transfers"
      get '(:client_type)/international_transfers/:typeid/', to: "international_transfers#show", defaults: {client_type: 1}, as: "international_transfer"
      post '(:client_type)/international_transfers/:typeid/commission_table', to: "international_transfers#commission_table", defaults: {client_type: 1}, as: "inter_commission_table"     
      post '(:client_type)/international_transfers/:typeid/calculate_commission_fee', to: "international_transfers#calculate_commission_fee", defaults: {client_type: 1}, as: "inter_calculate_commission_fee"  

      get '(:client_type)/local_transfers/', to: "local_transfers#index", defaults: {client_type: 1}, as: "local_transfers"

      get '(:client_type)/local_transfers/branch_transfers/', to: "local_transfers#show_branch_transfers", defaults: {client_type: 1}, as: "local_transfers_branch_transfers"
      post '(:client_type)/local_transfers/branch_transfers_commission_table', to: "local_transfers#branch_transfers_commission_table", defaults: {client_type: 1}, as: "branch_transfers_commission_table"     
      post '(:client_type)/local_transfers/branch_transfers_calculate_commission_fee', to: "local_transfers#branch_transfers_calculate_commission_fee", defaults: {client_type: 1}, as: "branch_transfers_calculate_commission_fee"  

      get '(:client_type)/local_transfers/cliring_gross/', to: "local_transfers#show_cliring_gross", defaults: {client_type: 1}, as: "local_transfers_cliring_gross"      
      post '(:client_type)/local_transfers/cliring_gross_calculate_commission_fee', to: "local_transfers#cliring_gross_calculate_commission_fee", defaults: {client_type: 1}, as: "cliring_gross_calculate_commission_fee"  

      get '(:client_type)/local_transfers/swift/', to: "local_transfers#show_swift", defaults: {client_type: 1}, as: "local_transfers_swift"
      post '(:client_type)/local_transfers/swift_calculate_commission_fee', to: "local_transfers#swift_calculate_commission_fee", defaults: {client_type: 1}, as: "swift_calculate_commission_fee"
    end

    get 'credit_types/(:client_type)', to: "credit_types#index", defaults: {client_type: 1}, as: "credit_purposes"
    get 'deposit_types/(:client_type)', to: "deposit_types#index", defaults: {client_type: 1}, as: "deposit_types"
    get 'transfer_types/(:client_type)', to: "transfer_types#index", defaults: {client_type: 1}, as: "transfer_types"
    get 'depository/(:client_type)', to: "depository#index", defaults: {client_type: 1}, as: "depository"

    post 'depository/(:client_type)/calculate_commission_fee', to: "depository#calculate_commission_fee", defaults: {client_type: 1}, as: "depository_calculate_commission_fee"
  end 


  get 'products/index'

  get 'credits(/:client_type(/:credit_type))', to: "credits#index", defaults: {client_type: 1, credit_type: 1}, as: "credits"

  get 'credits/show'

  get 'news/(:pageno)', to: "news#index", defaults: {pageno:1}, as: "news"
  get 'news/details/:id', to: "news#show", defaults: {:id=>1}, as: "news_details"


  get 'advice/index'

  get 'web_support/send_message'

  resources :rates

  root 'main#index'
  get 'main/index'

  resources :newsitems
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/controllers/products/credit_types/credits_controller.rb
class Products::CreditTypes::CreditsController < ApplicationController  
  before_action :add_def_breadcrumbs
  before_action :init_sidebar_data, only:[:index,:show]
  def index
    @credit_purpose = JSON.parse(Redis.current.get("credit_purposes")).select{|x| x["ID"] == params[:type_id].to_i}.first
    @credit_products = JSON.parse(Redis.current.get("credit_products")).select{|prod| prod["TypeID"]==params[:type_id].to_i and 
          (prod["IsForCompanies"] && params[:client_type].to_i==2 || prod["IsForIndividuals"] && params[:client_type].to_i==1)}
    @credit_types = CreditType.all    
  end
  def show
    add_breadcrumb "Типы кредитов", products_credit_types_credits_path(params[:client_type],params[:typeid])    
    @credit = JSON.parse(Redis.current.get("credit_products")).select{|c| c["ProductID"] == params["product_id"].to_i}.first
    @credit_interests = JSON.parse(Redis.current.get("credit_interests_#{@credit["ProductID"]}"));
    @user = Hash.new()
    @user[:name] = "username"
    
  end
  def calculate_rate_payment
    respond_to do |format|
      format.html { render plain: "custom action" }
      format.js {}
      format.json { render json: {"interest" => 18,"payment"=> 5699 } }
    end
  end

  def add_def_breadcrumbs
    add_breadcrumb "Главная страница", :root_path
    add_breadcrumb "Виды кредитов", products_credit_purposes_path(params[:client_type])
  end
end

app/controllers/products/credit_types_controller.rb
class Products::CreditTypesController < ApplicationController
  add_breadcrumb "Главная страница", :root_path
  before_action :init_sidebar_data, only:[:index]
  
  def index
  	@credit_purposes = JSON.parse(Redis.current.get("credit_purposes"))
  	@credit_types = CreditType.all
  
  end
end

app/controllers/products/deposit_types/deposits_controller.rb
class Products::DepositTypes::DepositsController < ApplicationController
  add_breadcrumb "Главная страница", :root_path
  before_action :add_def_breadcrumb
  before_action :init_sidebar_data, only:[:index,:show]
  
  def index    
    @deposit_type = JSON.parse(Redis.current.get("deposit_types")).select{|x| x["TypeID"] == params[:type_id].to_i}.first
    @deposit_products = JSON.parse(Redis.current.get("deposit_products"))
    @deposit_currencies = JSON.parse(Redis.current.get("deposit_currencies"))
  end
  def show
    add_breadcrumb "Типы депозитов", products_deposit_types_deposits_path(params[:client_type],params[:type_id])
    @deposit = JSON.parse(Redis.current.get("deposit_products")).select{|c| c["ProductID"] == params["product_id"].to_i}.first()
    @deposit_interests = JSON.parse(Redis.current.get("deposit_interests_#{@deposit["ProductID"]}"));    
  end
  def calculate_rate_payment
    respond_to do |format|
      format.js {}
    end
  end

  def add_def_breadcrumb
    add_breadcrumb "Виды депозитов", products_deposit_types_path(params[:client_type])
  end
end

app/controllers/products/deposit_types_controller.rb
class Products::DepositTypesController < ApplicationController
  add_breadcrumb "Главная страница", :root_path
  before_action :init_sidebar_data, only:[:index]
  def index
  	@abs_deposit_types = JSON.parse(Redis.current.get("deposit_types"))
  	@deposit_types = DepositType.all;
  end
end

app/controllers/products/depository_controller.rb
class Products::DepositoryController < ApplicationController
  add_breadcrumb "Главная страница", :root_path
  before_action :init_sidebar_data, only:[:index]
  def index
  	@safe_types = JSON.parse(Redis.current.get("safe_types"))
  	@safe_tariffs = JSON.parse(Redis.current.get("safe_tariffs")).select{|x| x["CustomerTypeID"]==params["client_type"].to_i}
  end
  def calculate_commission_fee    
    @safe_tariffs = JSON.parse(Redis.current.get("safe_tariffs")).select{|x| x["CustomerTypeID"]==params["client_type"].to_i}
    respond_to do |format|
      format.js {}
    end
  end
end

app/controllers/products/transfer_types/international_transfers_controller.rb
class Products::TransferTypes::InternationalTransfersController < ApplicationController
  add_breadcrumb "Главная страница", :root_path 
  before_action :add_def_breadcrumb, only:[:index,:show]  
  before_action :init_sidebar_data, only:[:index,:show]
  def index        
    @transfer_type_details = TransferTypeDetail.all
    @transfer_types = JSON.parse(Redis.current.get("transfer_types")).select{
      |x| x["GroupID"] == 1 && (x["IsForIndividuals"] && params["client_type"].to_i == 1 || x["IsForCompanies"] && params["client_type"].to_i == 2)
    }
  end
  def show    
    add_breadcrumb "Типы переводов", products_transfer_types_international_transfers_path(params["client_type"], params["typeid"])

    @transfer_type_details = TransferTypeDetail.find_by(typeid: params["typeid"])
    @transfer_commissions = TransferCommission.select{|commission| commission.typeid == params["typeid"].to_i && commission.currencyid == 840}
    @transfer_types = JSON.parse(Redis.current.get("transfer_types"))
    @transfer_type = @transfer_types.select{|x| x["TypeID"] == params["typeid"].to_i}.first
  end
  def commission_table
  	@transfer_commissions = TransferCommission.order(:minsum).select{|commission| commission.typeid == params["typeid"].to_i && 
      commission.currencyid == params["currencyid"].to_i && (commission.countryid == params["countryid"]||commission.countryid==-1)}
    respond_to do |format|    
      format.js {}
    end
  end
  def calculate_commission_fee
    @transfer_types = JSON.parse(Redis.current.get("transfer_types"))
  	respond_to do |format|      
      format.js {}      
    end
  end
  def add_def_breadcrumb
    add_breadcrumb "Виды переводов", products_transfer_types_path(params["client_type"])
  end 
end

app/controllers/products/transfer_types/local_transfers_controller.rb
class Products::TransferTypes::LocalTransfersController < ApplicationController  
    add_breadcrumb "Главная страница", :root_path 
  before_action :init_sidebar_data, only:[:index,:show_cliring_gross,:show_swift,:show_branch_transfers]
  before_action :add_def_breadcrumb, only:[:index,:show_cliring_gross,:show_swift,:show_branch_transfers]  
  def index        
    @transfer_type_details = TransferTypeDetail.all
    @transfer_types = JSON.parse(Redis.current.get("transfer_types")).select{
      |x| x["GroupID"] == 0 && (x["IsForIndividuals"] && params["client_type"].to_i == 1 || x["IsForCompanies"] && params["client_type"].to_i == 2)
    }
  end

  def show_branch_transfers
  	@branch_transfer_commissions = JSON.parse(Redis.current.get("branch_transfer_commissions"))
  	@regions = @branch_transfer_commissions.map{|x| {region_id: x["BranchID"], region_name: x["RegionName"]}}.uniq
  end
  
  def branch_transfers_commission_table
  	@branch_transfer_commissions = JSON.parse(Redis.current.get("branch_transfer_commissions"))
  	respond_to do |format|
      format.html { render plain: "commission_table" }
      format.json { render json: {"interest" => 18,"payment"=> 5699 } }
      format.js {}
    end
  end
  def branch_transfers_calculate_commission_fee
    @branch_transfer_commissions = JSON.parse(Redis.current.get("branch_transfer_commissions"))
  	respond_to do |format|
      format.html { render plain: "custom action" }
      format.js {}
      format.json { render json: {"interest" => 18,"payment"=> 5699 } }
    end
  end


  def show_cliring_gross
    @cliring_gross_commissions = JSON.parse(Redis.current.get("cliring_gross_commissions"))
  end
  
  def cliring_gross_calculate_commission_fee
    @cliring_gross_commissions = JSON.parse(Redis.current.get("cliring_gross_commissions"))
    respond_to do |format|
      format.html { render plain: "custom action" }
      format.js {}
      format.json { render json: {"interest" => 18,"payment"=> 5699 } }
    end
  end

  def show_swift
    @swift_commissions = JSON.parse(Redis.current.get("swift_commissions")).select{|x| x["CustomerTypeID"]==params["client_type"]}

  end
  
  def swift_calculate_commission_fee
    @swift_commissions = JSON.parse(Redis.current.get("swift_commissions"))
    respond_to do |format|
      format.html { render plain: "custom action" }
      format.js {}
      format.json { render json: {"interest" => 18,"payment"=> 5699 } }
    end
  end
  def add_def_breadcrumb
    add_breadcrumb "Виды переводов", products_transfer_types_path(params["client_type"])
  end 
end

app/controllers/products/transfer_types_controller.rb
class Products::TransferTypesController < ApplicationController
  add_breadcrumb "Главная страница", :root_path
  before_action :init_sidebar_data, only:[:index]
end

app/helpers/products/credit_types/credits_helper.rb
module Products::CreditTypes::CreditsHelper
end

app/helpers/products/credit_types_helper.rb
module Products::CreditTypesHelper
end

app/helpers/products/deposit_types/deposits_helper.rb
module Products::DepositTypes::DepositsHelper
	def GetDepositPeriods(product_id)
		@deposit_interests = JSON.parse(Redis.current.get("deposit_interests_#{product_id}"));    
		@deposit_interests.uniq{|x| x["MonthPeriod"]}.map{|x| x["MonthPeriod"]}
	end
	def GetDepositCurrencies(product_id)
		@deposit_interests = JSON.parse(Redis.current.get("deposit_interests_#{product_id}"));    
		@deposit_interests.uniq{|x| x["CurrencyID"]}.map{|x| x["CurrencyID"]}
	end
end

app/helpers/products/deposit_types_helper.rb
module Products::DepositTypesHelper
	def GetDepositTypeDetails type_id
		@details = @deposit_type_details.select{|details| details.type_id == type_id}.first		
		return @details
	end
end

app/helpers/products/depositary_helper.rb
module Products::DepositaryHelper
end

app/helpers/products/transfer_types/international_transfers_helper.rb
module Products::TransferTypes::InternationalTransfersHelper
end

app/helpers/products/transfer_types/local_transfers_helper.rb
module Products::TransferTypes::LocalTransfersHelper
	def GetPaymentType(payment_typeid)
		case payment_typeid
		when 1 
			'выдача через кассу'
		when 2 
			'на расчетный счет'
		when 3 
			'на погашение кредита'
		end 
	end
	def GetPayinType(payment_typeid)
		case payment_typeid
		when 1 
			'отправка через кассу'
		when 2 
			'отправка с расчетного счета'
		end 
	end
end

app/helpers/products/transfer_types_helper.rb
module Products::TransferTypesHelper
  def GetTransferTypeDetails typeid
    @details = @transfer_type_details.select{|details| details.typeid == typeid}.first
    return @details
  end
  def GetCommissionFees summa, currencyid, countryid
    commission_ids = CountriesofCommission.where(countryid: countryid).map{|commission| commission.transfer_commission_id}

    transfer_commissions = TransferCommission.where("id in (?) and currencyid = ? and minsum<=#{summa} and #{summa}<=maxsum", commission_ids, currencyid)
    return transfer_commissions
  end
  def GetCommissionFee typeid, summa, currencyid, countryid
    transfer_commissions = TransferCommission.where("typeid=? and countryid=? and currencyid = ? and minsum<=#{summa} and #{summa}<=maxsum", typeid,countryid, currencyid)
    if(transfer_commissions.count>0)
      return transfer_commissions.first
    else
        transfer_commissions = TransferCommission.where("typeid=? and countryid=? and currencyid = ? and minsum<=#{summa} and #{summa}<=maxsum", typeid,-1, currencyid)
        return transfer_commissions.first
    end
    return nil;
  end
end 

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/depository/calculate_commission_fee.js.erb
<% commission = @safe_tariffs.select{|x| x["SafeTypeID"] == params["safetypeid"].to_i and 
        	x["DaysFrom"]<=params["dayscount"].to_i and params["dayscount"].to_i<=x["DaysTo"]}.first %>
<% if(commission!=nil) %>	
		$('#safe_cost').val(<%=commission["SummPerDay"]%>+' сом')		
		$('#total_cost').val(<%=commission["SummPerDay"]*params["dayscount"].to_i%>+ ' сом')
<% end %>

app/views/products/depository/index.html.erb
<%= render layout: "shared/one_column_sidebar", locals:{title:"Сейфовые ячейки", subtitle:params["client_type"].to_i == 2?"Корпоративным клиентам": "Частным клиентам"} do %>
  <h2 id="credit_interest_rates"><i class="fa fa-percent" aria-hidden="true"></i>  Тарифы</h2>
  <div class="panel panel-default">
    <div class="panel-body">
      <div id="commissions_table">
        <div class="panel panel-warning">
          <!-- Default panel contents -->
          <% @safe_types.each do |safetype|%>
            <div class="panel-heading"><%=safetype["TypeName"]%></div>
            <!-- Table -->
            <table class="table">
              <tr>
                <th>Период(кол-во дней)</th>
                <th>Стоимость за каждый день</th>
              </tr>
              <% @safe_tariffs.select{|x| x["SafeTypeID"]==safetype["TypeID"]}.each do |tariff|%>
                <tr>
                  <td>
                    <%=tariff["DaysFrom"]%>-<%=tariff["DaysTo"]%>
                  </td>
                  <td><%= tariff["SummPerDay"]%> сом</td>
                </tr>
              <% end %>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <h2><i class="fa fa-calculator" aria-hidden="true"></i>Рассчитайте комиссию перевода</h2>
  <div class="panel panel-warning">
    <div class="panel-body">
      <%= form_tag(products_transfer_types_branch_transfers_calculate_commission_fee_path, remote: true, method: "post", class: "nifty_form") do %>
        <div class = "container-fluid">
          <div class="row">
            <div class="col-lg-4">
              <div class="form-group">
                <%= label_tag(:dayscount, "Количество дней:") %>
                <%= text_field_tag(:dayscount, "0", class: "form-control") %>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="form-group">
                <div class="btn-group" role="group" aria-label="..." id="calculator_safesize">
                  <b>Размер сейфа:</b><Br/>
                  <% @safe_types.each do |safetype|%>
                    <button type="button" class="btn <%= 'btn-danger' if @safe_types.first==safetype %> <%= 'btn-default' if @safe_types.first!=safetype %>" data-safetypeid=<%= safetype["TypeID"]%> style="margin-top:3px; width:100%;"><%= safetype["TypeName"]%></button><Br/>
                  <% end %>
                </div>
              </div>
            </div>
            <div class='col-lg-4'>
              <div class="form-group">
                <b>Стоимость сейфа:</b><Br/>
                <div class="panel panel-primary">
                  <div class="panel-body">
                    <%= label_tag(:safe_cost, "За один день:") %>
                    <%= text_field_tag(:safe_cost, "0", class: "form-control") %>
                    <%= label_tag(:total_cost, "За период:") %>
                    <%= text_field_tag(:total_cost, "0", class: "form-control") %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $(document).ready(function() {
                            calcCommissions = function ()
                            {
                              $.ajax({
                                url: "<%= products_depository_calculate_commission_fee_path(params["client_type"])%>",
                                method: 'POST',
                                dataType: "script",
                                data: {
                                  dayscount: $('#dayscount').val(),
                                  safetypeid: $('#calculator_safesize > .btn-danger').data("safetypeid"),
                                },
                              success: function(data, textStatus) {},
                              error: function() {}
                            });
                          }
                            $("#dayscount").on('change keyup paste', calcCommissions);
                           });
                    $("#calculator_safesize > button").on("click", function(){
                        $("#calculator_safesize > .btn-danger").removeClass("btn-danger").addClass("btn-default")
                        $(this).addClass("btn-danger")
                        calcCommissions.call()
                      });
</script>