config/routes.rb
Rails.application.routes.draw do

  get 'management/index', as: "management"

  get 'special_offers/index', as: "special_offers"
  get 'special_offers/show/:id', to:"special_offers#show", as: "special_offer"
  get 'mini_special_offers/index', as: "mini_special_offers"
  get 'mini_special_offers/show/:id', to:"mini_special_offers#show", as: "mini_special_offer"

  namespace :admin do
    get 'deposit_types/show'
  end

  namespace :admin do
    get 'deposit_types/edit'
  end

  namespace :admin do
    get '/news', to:"news#index", as: "newsitems"
    get '/news/new', to:"news#new", as: "newsitem_new"
    post '/news', to:"news#create", as: "newsitem_create" 
    get '/news/:id', to:"news#show", as: "newsitem_show"
    get '/news/:id/edit', to:"news#edit", as: "newsitem_edit"
    patch '/news/:id', to:"news#update", as: "newsitem_update"
    delete '/news/:id', to:"news#delete", as: "newsitem_delete"
    
    post '/garants/add_image', to:"garants#add_image", as: "garant_images"
    post '/garants/add_detail', to:"garants#add_detail", as: "garant_details"
    post '/garants/destroy_image/:id/:image_id', to:"garants#destroy_image", as: "destroy_garant_image"
    post '/garants/destroy_detail/:id/:detail_id', to:"garants#destroy_detail", as: "destroy_garant_detail"
    resources :cash_terminals
    resources :garants
    resources :deposit_types
    resources :credit_types
    resources :credit_types
    resources :special_offers
    resources :mini_special_offers
    resources :offices
    resources :managers
    root "offices#index"

  end

  get 'garant/index', as: "garants"
  get 'garant/:garantid', to: "garant#show", as: "garant_show"

  get 'posterminals/index', as: "posterminals"

  get 'cards/index', as: "cards"

  get 'internetbank/index', as: "internetbank"

  get 'corraccounts/index', as: "corraccounts"

  get 'bankdetails/index', as: "bankdetails" 

  get 'report/index', as: "reports"

  get 'office/index', as: "offices"

  post 'office/show', as: "show_office_info"

  resources :users 
  
  post 'users/custom'

  namespace :products do
    namespace :credit_types do
      get 'credits(/:client_type(/:type_id))', to: "credits#index", defaults: {client_type: 1, type_id: 1}, as: "credits"
      get 'credits(/:client_type(/:type_id))/:product_id', to: "credits#show", defaults: {product_id: -1}, as: "creditdetails"
      post 'credits(/:client_type(/:type_id))/:product_id/calculate_rate_payment', to: "credits#calculate_rate_payment", defaults: {product_id: -1}, as: "calculate_rate_payment"
    end

    namespace :deposit_types do
      get 'deposits(/:client_type(/:type_id))', to: "deposits#index", defaults: {client_type: 1, type_id: 1}, as: "deposits"
      get 'deposits(/:client_type(/:type_id))/:product_id', to: "deposits#show", defaults: {product_id: -1}, as: "depositdetails"
      post 'deposits(/:client_type(/:type_id))/:product_id/calculate_rate_payment', to: "deposits#calculate_rate_payment", defaults: {product_id: -1}, as: "calculate_rate_payment"
    end

    namespace :transfer_types do 
      get '(:client_type)/international_transfers/', to: "international_transfers#index", defaults: {client_type: 1}, as: "international_transfers"
      get '(:client_type)/international_transfers/:typeid/', to: "international_transfers#show", defaults: {client_type: 1}, as: "international_transfer"
      post '(:client_type)/international_transfers/:typeid/commission_table', to: "international_transfers#commission_table", defaults: {client_type: 1}, as: "inter_commission_table"     
      post '(:client_type)/international_transfers/:typeid/calculate_commission_fee', to: "international_transfers#calculate_commission_fee", defaults: {client_type: 1}, as: "inter_calculate_commission_fee"  

      get '(:client_type)/local_transfers/', to: "local_transfers#index", defaults: {client_type: 1}, as: "local_transfers"

      get '(:client_type)/local_transfers/branch_transfers/', to: "local_transfers#show_branch_transfers", defaults: {client_type: 1}, as: "local_transfers_branch_transfers"
      post '(:client_type)/local_transfers/branch_transfers_commission_table', to: "local_transfers#branch_transfers_commission_table", defaults: {client_type: 1}, as: "branch_transfers_commission_table"     
      post '(:client_type)/local_transfers/branch_transfers_calculate_commission_fee', to: "local_transfers#branch_transfers_calculate_commission_fee", defaults: {client_type: 1}, as: "branch_transfers_calculate_commission_fee"  

      get '(:client_type)/local_transfers/cliring_gross/', to: "local_transfers#show_cliring_gross", defaults: {client_type: 1}, as: "local_transfers_cliring_gross"      
      post '(:client_type)/local_transfers/cliring_gross_calculate_commission_fee', to: "local_transfers#cliring_gross_calculate_commission_fee", defaults: {client_type: 1}, as: "cliring_gross_calculate_commission_fee"  

      get '(:client_type)/local_transfers/swift/', to: "local_transfers#show_swift", defaults: {client_type: 1}, as: "local_transfers_swift"
      post '(:client_type)/local_transfers/swift_calculate_commission_fee', to: "local_transfers#swift_calculate_commission_fee", defaults: {client_type: 1}, as: "swift_calculate_commission_fee"
    end

    get 'credit_types/(:client_type)', to: "credit_types#index", defaults: {client_type: 1}, as: "credit_purposes"
    get 'deposit_types/(:client_type)', to: "deposit_types#index", defaults: {client_type: 1}, as: "deposit_types"
    get 'transfer_types/(:client_type)', to: "transfer_types#index", defaults: {client_type: 1}, as: "transfer_types"
    get 'depository/(:client_type)', to: "depository#index", defaults: {client_type: 1}, as: "depository"

    post 'depository/(:client_type)/calculate_commission_fee', to: "depository#calculate_commission_fee", defaults: {client_type: 1}, as: "depository_calculate_commission_fee"
  end 


  get 'products/index'

  get 'credits(/:client_type(/:credit_type))', to: "credits#index", defaults: {client_type: 1, credit_type: 1}, as: "credits"

  get 'credits/show'

  get 'news/(:pageno)', to: "news#index", defaults: {pageno:1}, as: "news"
  get 'news/details/:id', to: "news#show", defaults: {:id=>1}, as: "news_details"


  get 'advice/index'

  get 'web_support/send_message'

  resources :rates

  root 'main#index'
  get 'main/index'

  resources :newsitems
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/garant.rb
class Garant < ApplicationRecord
	has_many :garant_details
	has_many :garant_images
end

app/controllers/admin/garants_controller.rb
class Admin::GarantsController < ApplicationController
  layout "admin_application"
  before_action :set_garant, only: [:show, :edit, :update, :destroy, :destroy_image, :destroy_detail]

  # GET /garants
  # GET /garants.json
  def index
    @garants = Garant.all
  end

  # GET /garants/1
  # GET /garants/1.json
  def show
    @garant_image = GarantImage.new(garant_id: params[:id].to_i)
    @garant_detail = GarantDetail.new(garant_id: params[:id].to_i)
  end

  # GET /garants/new
  def new
    @garant = Garant.new
  end

  # GET /garants/1/edit
  def edit
  end

  # POST /garants
  # POST /garants.json
  def create
    @garant = Garant.new(garant_params)

    respond_to do |format|
      if @garant.save
        format.html { redirect_to admin_garant_path(@garant), notice: 'Garant was successfully created.' }
        format.json { render :show, status: :created, location: @garant }
      else
        format.html { render :new }
        format.json { render json: @garant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /garants/1
  # PATCH/PUT /garants/1.json
  def update
    respond_to do |format|
      if @garant.update(garant_params)
        format.html { redirect_to admin_garant_path(@garant), notice: 'Garant was successfully updated.' }
        format.json { render :show, status: :ok, location: @garant }
      else
        format.html { render :edit }
        format.json { render json: @garant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garants/1
  # DELETE /garants/1.json
  def destroy
    @garant.destroy
    respond_to do |format|
      format.html { redirect_to admin_garants_path, notice: 'Garant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_image
    @garant_image = GarantImage.new(garant_image_params)
    respond_to do |format|
      if @garant_image.save
        format.html { redirect_to admin_garant_path(@garant_image.garant), notice: 'Mini Special offer was successfully created.' }
        format.json { render :show, status: :created, location: @garant_image }
      else
        format.html { render :new }
        format.json { render json: @garant_image.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy_image
    @garant_image = GarantImage.find(params[:image_id])
    @garant_image.destroy
    respond_to do |format|
        format.html { redirect_to admin_garant_path(@garant), notice: 'Garant image was successfully destroyed.' }              
    end
  end
  def add_detail
    @garant_detail = GarantDetail.new(garant_detail_params)
    respond_to do |format|
      if @garant_detail.save
        format.html { redirect_to admin_garant_path(@garant_detail.garant), notice: 'Garant detail was successfully created.' }
        format.json { render :show, status: :created, location: @garant_detail }
      else
        format.html { render :new }
        format.json { render json: @garant_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy_detail
    @garant_detail = GarantDetail.find(params[:detail_id])
    @garant_detail.destroy
    respond_to do |format|
        format.html { redirect_to admin_garant_path(@garant), notice: 'Garant detail was successfully destroyed.' }              
    end
  end
  def garant_image_params
    params.require(:garant_image).permit(:garant_id, :image_description, :image)
  end
  def garant_detail_params
    params.require(:garant_detail).permit(:garant_id, :prop_key, :prop_value)
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_garant
    @garant = Garant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def garant_params
    params.require(:garant).permit(:name, :description, :cost, :region, :phone)
  end
end

app/controllers/garant_controller.rb
class GarantController < ApplicationController
  add_breadcrumb "Главная страница", :root_path
  before_action :init_sidebar_data, only:[:index,:show]
  def index
  	@garants = Garant.all
  end
  def show 
  	add_breadcrumb "Реализация залогового обеспечения", garants_path()
  	@garant = Garant.first
  end 
end

app/helpers/admin/garants_helper.rb
module Admin::GarantsHelper
end

app/helpers/garant_helper.rb
module GarantHelper
end

app/views/admin/garants/_form.html.erb
<%= form_for([:admin, garant]) do |f| %>
  <% if garant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garant.errors.count, "error") %> prohibited this garant from being saved:</h2>

      <ul>
      <% garant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">    
    <%= f.label :name, "Название" %>
    <%= f.text_field :name, class:"form-control"%>
  </div>
  <div class="form-group">    
    <%= f.label :description, "Описание" %>
    <%= f.text_area :description, class:"form-control", rows:25 %>
  </div>
  <div class="form-group">
    <%= f.label :cost, "Стоимость" %>
    <%= f.text_field :cost, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :region, "Стоимость" %>
    <%= f.text_field :region, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить"%>
  </div>
<% end %>

app/views/admin/garants/_form_garant_detail.html.erb
<%= form_for([:admin, garant_detail]) do |f| %>
  <% if garant_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garant_detail.errors.count, "error") %> prohibited this garant_detail from being saved:</h2>

      <ul>
      <% garant_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">    
    <%= f.label :prop_key, "Поле" %>
    <%= f.text_field :prop_key, class:"form-control"%>
    <%= f.hidden_field :garant_id %>
  </div>
  <div class="form-group">    
    <%= f.label :prop_value, "Значение" %>
    <%= f.text_field :prop_value, class:"form-control"%>
  </div>

  <div class="actions">
    <%= f.submit "Добавить"%>
  </div>
<% end %>

app/views/admin/garants/_form_garant_image.html.erb
<%= form_for([:admin, garant_image]) do |f| %>
  <% if garant_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garant_image.errors.count, "error") %> prohibited this garant_image from being saved:</h2>

      <ul>
      <% garant_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">    
    <%= f.label :image_description, "Описание рисунка" %>
    <%= f.text_field :image_description, class:"form-control"%>
    <%= f.hidden_field :garant_id %>
  </div>

  <div class="form-group">
    <label for="image">Изображение</label>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit "Добавить"%>
  </div>
<% end %>

app/views/admin/garants/edit.html.erb
<h1>Editing Garant</h1>

<%= render 'form', garant: @garant %>

<%= link_to 'Показать', admin_garant_path(@garant) %> |
<%= link_to 'Назад к списку', admin_garants_path %>

app/views/admin/garants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Реализация залогового имущества</h1>

<%= link_to 'Добавить залоговое имущество', new_admin_garant_path %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Название</th>
      <th>Описание</th>
      <th>Стоимость</th>
      <th>Место расположения</th>
      <th>Номер телефона</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @garants.each do |garant| %>
      <tr>
        <td><%= garant.name %></td>
        <td><%= garant.description %></td>
        <td><%= garant.cost %></td>
        <td><%= garant.region %></td>
        <td><%= garant.phone %></td>
        <td><%= link_to 'Показать', admin_garant_path(garant) %></td>
        <td><%= link_to 'Измнеить', edit_admin_garant_path(garant) %></td>
        <td><%= link_to 'Удалить', admin_garant_path(garant), method: :delete, data: { confirm: 'Вы действительно хотите удалить?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/garants/new.html.erb
<h1>New Garant</h1>

<%= render 'form', garant: @garant %>

<%= link_to 'Отменить и перейти к списку', garants_path %>

app/views/admin/garants/show.html.erb
<%= render "shared/garant", garant:@garant %>
<br/> 
<div class="panel panel-primary">
  <div class="panel-heading">Фотографии</div>
  <div class="panel-body">
  <table class="table">
  <% @garant.garant_images.each do |gi|%>  
  <tr>
  <td><%=image_tag(gi.image.url(:small))%></td>
  <td><%=gi.image_description%></td>
  <td><%= link_to 'Удалить', admin_destroy_garant_image_path(gi.garant_id,gi.id), method: :post, data: { confirm: 'Вы действительно хотите удалить?' } %></td>
  </tr>
  <% end %>
  </table>
  <hr>
  <h4>Добавление фотографии</h4>
<%= render "form_garant_image", garant_image: @garant_image %>   
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">Добавить характеристику</div>
  <div class="panel-body">
  <table class="table">
  <% @garant.garant_details.each do |gd|%>  
  <tr>
  <td><%=gd.prop_key%></td>
  <td><%=gd.prop_value%></td>
  <td><%= link_to 'Удалить', admin_destroy_garant_detail_path(gd.garant_id,gd.id), method: :post, data: { confirm: 'Вы действительно хотите удалить?' } %></td>
  </tr>
  <% end %>
  </table>
  <hr>
  <h4>Добавление свойств</h4>
<%= render "form_garant_detail", garant_detail: @garant_detail %>   
  </div>
</div>
<%= link_to 'Измнеить', edit_admin_garant_path(@garant) %> |
<%= link_to 'Назад к списку', admin_garants_path %>