config/routes.rb
Rails.application.routes.draw do

  get 'management/index', as: "management"

  get 'special_offers/index', as: "special_offers"
  get 'special_offers/show/:id', to:"special_offers#show", as: "special_offer"
  get 'mini_special_offers/index', as: "mini_special_offers"
  get 'mini_special_offers/show/:id', to:"mini_special_offers#show", as: "mini_special_offer"

  namespace :admin do
    get 'deposit_types/show'
  end

  namespace :admin do
    get 'deposit_types/edit'
  end

  namespace :admin do
    get '/news', to:"news#index", as: "newsitems"
    get '/news/new', to:"news#new", as: "newsitem_new"
    post '/news', to:"news#create", as: "newsitem_create" 
    get '/news/:id', to:"news#show", as: "newsitem_show"
    get '/news/:id/edit', to:"news#edit", as: "newsitem_edit"
    patch '/news/:id', to:"news#update", as: "newsitem_update"
    delete '/news/:id', to:"news#delete", as: "newsitem_delete"
    
    post '/garants/add_image', to:"garants#add_image", as: "garant_images"
    post '/garants/add_detail', to:"garants#add_detail", as: "garant_details"
    post '/garants/destroy_image/:id/:image_id', to:"garants#destroy_image", as: "destroy_garant_image"
    post '/garants/destroy_detail/:id/:detail_id', to:"garants#destroy_detail", as: "destroy_garant_detail"
    resources :cash_terminals
    resources :garants
    resources :deposit_types
    resources :credit_types
    resources :credit_types
    resources :special_offers
    resources :mini_special_offers
    resources :offices
    resources :managers
    root "offices#index"

  end

  get 'garant/index', as: "garants"
  get 'garant/:garantid', to: "garant#show", as: "garant_show"

  get 'posterminals/index', as: "posterminals"

  get 'cards/index', as: "cards"

  get 'internetbank/index', as: "internetbank"

  get 'corraccounts/index', as: "corraccounts"

  get 'bankdetails/index', as: "bankdetails" 

  get 'report/index', as: "reports"

  get 'office/index', as: "offices"

  post 'office/show', as: "show_office_info"

  resources :users 
  
  post 'users/custom'

  namespace :products do
    namespace :credit_types do
      get 'credits(/:client_type(/:type_id))', to: "credits#index", defaults: {client_type: 1, type_id: 1}, as: "credits"
      get 'credits(/:client_type(/:type_id))/:product_id', to: "credits#show", defaults: {product_id: -1}, as: "creditdetails"
      post 'credits(/:client_type(/:type_id))/:product_id/calculate_rate_payment', to: "credits#calculate_rate_payment", defaults: {product_id: -1}, as: "calculate_rate_payment"
    end

    namespace :deposit_types do
      get 'deposits(/:client_type(/:type_id))', to: "deposits#index", defaults: {client_type: 1, type_id: 1}, as: "deposits"
      get 'deposits(/:client_type(/:type_id))/:product_id', to: "deposits#show", defaults: {product_id: -1}, as: "depositdetails"
      post 'deposits(/:client_type(/:type_id))/:product_id/calculate_rate_payment', to: "deposits#calculate_rate_payment", defaults: {product_id: -1}, as: "calculate_rate_payment"
    end

    namespace :transfer_types do 
      get '(:client_type)/international_transfers/', to: "international_transfers#index", defaults: {client_type: 1}, as: "international_transfers"
      get '(:client_type)/international_transfers/:typeid/', to: "international_transfers#show", defaults: {client_type: 1}, as: "international_transfer"
      post '(:client_type)/international_transfers/:typeid/commission_table', to: "international_transfers#commission_table", defaults: {client_type: 1}, as: "inter_commission_table"     
      post '(:client_type)/international_transfers/:typeid/calculate_commission_fee', to: "international_transfers#calculate_commission_fee", defaults: {client_type: 1}, as: "inter_calculate_commission_fee"  

      get '(:client_type)/local_transfers/', to: "local_transfers#index", defaults: {client_type: 1}, as: "local_transfers"

      get '(:client_type)/local_transfers/branch_transfers/', to: "local_transfers#show_branch_transfers", defaults: {client_type: 1}, as: "local_transfers_branch_transfers"
      post '(:client_type)/local_transfers/branch_transfers_commission_table', to: "local_transfers#branch_transfers_commission_table", defaults: {client_type: 1}, as: "branch_transfers_commission_table"     
      post '(:client_type)/local_transfers/branch_transfers_calculate_commission_fee', to: "local_transfers#branch_transfers_calculate_commission_fee", defaults: {client_type: 1}, as: "branch_transfers_calculate_commission_fee"  

      get '(:client_type)/local_transfers/cliring_gross/', to: "local_transfers#show_cliring_gross", defaults: {client_type: 1}, as: "local_transfers_cliring_gross"      
      post '(:client_type)/local_transfers/cliring_gross_calculate_commission_fee', to: "local_transfers#cliring_gross_calculate_commission_fee", defaults: {client_type: 1}, as: "cliring_gross_calculate_commission_fee"  

      get '(:client_type)/local_transfers/swift/', to: "local_transfers#show_swift", defaults: {client_type: 1}, as: "local_transfers_swift"
      post '(:client_type)/local_transfers/swift_calculate_commission_fee', to: "local_transfers#swift_calculate_commission_fee", defaults: {client_type: 1}, as: "swift_calculate_commission_fee"
    end

    get 'credit_types/(:client_type)', to: "credit_types#index", defaults: {client_type: 1}, as: "credit_purposes"
    get 'deposit_types/(:client_type)', to: "deposit_types#index", defaults: {client_type: 1}, as: "deposit_types"
    get 'transfer_types/(:client_type)', to: "transfer_types#index", defaults: {client_type: 1}, as: "transfer_types"
    get 'depository/(:client_type)', to: "depository#index", defaults: {client_type: 1}, as: "depository"

    post 'depository/(:client_type)/calculate_commission_fee', to: "depository#calculate_commission_fee", defaults: {client_type: 1}, as: "depository_calculate_commission_fee"
  end 


  get 'products/index'

  get 'credits(/:client_type(/:credit_type))', to: "credits#index", defaults: {client_type: 1, credit_type: 1}, as: "credits"

  get 'credits/show'

  get 'news/(:pageno)', to: "news#index", defaults: {pageno:1}, as: "news"
  get 'news/details/:id', to: "news#show", defaults: {:id=>1}, as: "news_details"


  get 'advice/index'

  get 'web_support/send_message'

  resources :rates

  root 'main#index'
  get 'main/index'

  resources :newsitems
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/deposit_type.rb
class DepositType < ApplicationRecord
  has_attached_file :image, styles: { small: "64x64", med: "128x128", large: "520x270" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validate :file_dimensions
  private

  def file_dimensions(width = 620, height = 270)
    if image!=nil && image.queued_for_write[:original]!=nil
      dimensions = Paperclip::Geometry.from_file(image.queued_for_write[:original].path)
      unless dimensions.width == width && dimensions.height == height
        errors.add :image, "Width must be #{width}px and height must be #{height}px"
      end
    end
  end
end

app/controllers/admin/deposit_types_controller.rb
class Admin::DepositTypesController < ApplicationController
  layout "admin_application"
  before_action :set_deposit_type, only: [:show, :edit, :update, :destroy]

  # GET /deposit_types
  # GET /deposit_types.json
  def index
    @deposit_types = DepositType.all
    @abs_deposit_types = JSON.parse(Redis.current.get("deposit_types"))
  end

  # GET /deposit_types/1
  # GET /deposit_types/1.json
  def show
  end

  # GET /deposit_types/1/edit
  def edit    
  end

  # PATCH/PUT /deposit_types/1
  # PATCH/PUT /deposit_types/1.json
  def update
    respond_to do |format|
      if @deposit_type.update(deposit_type_params)
        format.html { redirect_to admin_deposit_type_path(@deposit_type), notice: 'Deposit type was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposit_type }
      else
        format.html { render :edit }
        format.json { render json: @deposit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deposit_type
      @deposit_type = DepositType.find(params[:id])
      @abs_deposit_type = JSON.parse(Redis.current.get("deposit_types")).select{|x| x["TypeID"]==@deposit_type.type_id}.first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deposit_type_params
      params.require(:deposit_type).permit(:caption, :description, :footer, :image)
    end
end

app/controllers/products/deposit_types/deposits_controller.rb
class Products::DepositTypes::DepositsController < ApplicationController
  add_breadcrumb "Главная страница", :root_path
  before_action :add_def_breadcrumb
  before_action :init_sidebar_data, only:[:index,:show]
  
  def index    
    @deposit_type = JSON.parse(Redis.current.get("deposit_types")).select{|x| x["TypeID"] == params[:type_id].to_i}.first
    @deposit_products = JSON.parse(Redis.current.get("deposit_products"))
    @deposit_currencies = JSON.parse(Redis.current.get("deposit_currencies"))
  end
  def show
    add_breadcrumb "Типы депозитов", products_deposit_types_deposits_path(params[:client_type],params[:type_id])
    @deposit = JSON.parse(Redis.current.get("deposit_products")).select{|c| c["ProductID"] == params["product_id"].to_i}.first()
    @deposit_interests = JSON.parse(Redis.current.get("deposit_interests_#{@deposit["ProductID"]}"));    
  end
  def calculate_rate_payment
    respond_to do |format|
      format.js {}
    end
  end

  def add_def_breadcrumb
    add_breadcrumb "Виды депозитов", products_deposit_types_path(params[:client_type])
  end
end

app/controllers/products/deposit_types_controller.rb
class Products::DepositTypesController < ApplicationController
  add_breadcrumb "Главная страница", :root_path
  before_action :init_sidebar_data, only:[:index]
  def index
  	@abs_deposit_types = JSON.parse(Redis.current.get("deposit_types"))
  	@deposit_types = DepositType.all;
  end
end

app/helpers/admin/deposit_types_helper.rb
module Admin::DepositTypesHelper
end

app/helpers/products/deposit_types/deposits_helper.rb
module Products::DepositTypes::DepositsHelper
	def GetDepositPeriods(product_id)
		@deposit_interests = JSON.parse(Redis.current.get("deposit_interests_#{product_id}"));    
		@deposit_interests.uniq{|x| x["MonthPeriod"]}.map{|x| x["MonthPeriod"]}
	end
	def GetDepositCurrencies(product_id)
		@deposit_interests = JSON.parse(Redis.current.get("deposit_interests_#{product_id}"));    
		@deposit_interests.uniq{|x| x["CurrencyID"]}.map{|x| x["CurrencyID"]}
	end
end

app/helpers/products/deposit_types_helper.rb
module Products::DepositTypesHelper
	def GetDepositTypeDetails type_id
		@details = @deposit_type_details.select{|details| details.type_id == type_id}.first		
		return @details
	end
end

app/views/products/deposit_types/deposits/index.html.erb
<%= render layout: "shared/one_column_sidebar", locals:{title: @deposit_type["Name"], subtitle: params["client_type"].to_i == 2?"Корпоративным клиентам": "Частным клиентам"} do %>
  <% @deposit_products.select{|prod| prod["TypeID"]==params[:type_id].to_i && prod["OrganizationTypeID"] == params[:client_type].to_i }.each do |product| %>
    <div class="rate">&le;<%=product["MaxRate"]%></div>
    <h3 style="color: #d40000;"><%=product["Name"]%></h3>
    <article>
      <p>
        <%=product["Description"]%>
      </p>
    </article>
    <table class="table table-striped">
      <tbody>
        <% @deposit_currencies.select{|depcurr| depcurr["ProductID"]==product["ProductID"] }.each do |depcurr| %>
          <tr>
            <td><%= GetCurrencyName(depcurr["CurrencyID"])%></td>
            <td><%= depcurr["MinPeriod"]%>-<%= depcurr["MaxPeriod"]%>мес.</td>
            <td><%= depcurr["MinRate"]%>-<%= depcurr["MaxRate"]%>%</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div style="float:right; margin-bottom:15px;"><a href="<%=products_deposit_types_depositdetails_path(params[:client_type],params[:type_id],product["ProductID"])%>" >Подробнее <i class="fa fa-chevron-right" aria-hidden="true"></i></a></div>
    <div style="clear:both;"></div>
  <% end %>
<% end %>

app/views/products/deposit_types/deposits/show.html.erb
<%= render layout: "shared/one_column_sidebar", locals:{title: @deposit["Name"], subtitle: params["client_type"].to_i == 2?"Корпоративным клиентам": "Частным клиентам"} do %>
  <div class="process">
    <div class="process-row">
      <div class="process-step">
        <button type="button" class="btn btn-default btn-circle" disabled="disabled"><i class="fa fa-percent fa-3x"></i></button>
        <p>Изучите <br>
          процентные ставки</p>
      </div>
      <div class="process-step">
        <button type="button" class="btn btn-default btn-circle" disabled="disabled"><i class="fa fa-calculator fa-3x"></i></button>
        <p>Рассчитайте <br>
          размер платежа</p>
      </div>
      <div class="process-step">
        <button type="button" class="btn btn-default btn-circle" disabled="disabled"><i class="fa fa-wpforms fa-3x"></i></button>
        <p>Заполните <br>
          онлайн анкету</p>
      </div>
      <div class="process-step">
        <button type="button" class="btn btn-default btn-circle" disabled="disabled"><i class="fa fa-phone fa-3x"></i></button>
        <p>Дождитесь <br>
          звонка оператора</p>
      </div>
      <div class="process-step">
        <button type="button" class="btn btn-success btn-circle" disabled="disabled"><i class="fa fa-thumbs-up fa-3x"></i></button>
        <p>Получите кредит <br>
          на выгодных условиях</p>
      </div>
    </div>
  </div>
  <h2 id="credit_interest_rates"><i class="fa fa-percent" aria-hidden="true"></i>  Процентные ставки</h2>
  <div class="panel panel-primary">
    <div class="panel-body">
      <div class="table-responsive">
        <table class = 'table table-responsive'>
          <thead>
            <tr>
              <th></th>
              <% GetDepositPeriods(@deposit["ProductID"]).each do |period| %>
                <th><%= period %> мес.</th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% GetDepositCurrencies(@deposit["ProductID"]).each do |currency_id| %>
              <tr>
                <td><%= GetCurrencyName(currency_id) %></td>
                <% GetDepositPeriods(@deposit["ProductID"]).each do |period| %>
                  <% rate = @deposit_interests.select{|r| r["CurrencyID"]==currency_id and r["MonthPeriod"]==period }.first()%>
                  <td>
                    <% if rate!=nil %>
                      <%= trim_zero(rate["InterestRate"]) %>%
          <% else %>
                      -
          <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <h2><i class="fa fa-calculator" aria-hidden="true"></i> Рассчитайте размер платежа </h2>
  <div class="panel panel-primary">
    <div class="panel-body">
      <%= form_tag({controller: "deposits", action: "calculate_rate_payment"}, remote: true, method: "post", class: "nifty_form") do %>
        <div class = "container-fluid">
          <div class = "row">
            <div class ="col-lg-6">
              <div class="form-group">
                <%= label_tag(:summa, "Сумма вклада:") %>
                <%= text_field_tag(:summa, "", class: "form-control", id: "txtdepositsum", type: "number", placeholder: "Введите сумму вклада")%>
              </div>
              <div class="form-group">
                <label>Валюта:</label><br/>
                <% depositcurrs = GetDepositCurrencies(@deposit["ProductID"])%>
                <% depositcurrs.each do |currency_id| %>
                  <%= label_tag("currency_id_#{currency_id}", GetCurrencyName(currency_id), class: "radio-inline") do %>
                    <%= radio_button_tag(:currency_id, "#{currency_id}", currency_id == depositcurrs.first)%>
                    <%= GetCurrencyName(currency_id) %>
                  <% end %>
                <% end %>
              </div>
              <div class="form-group">
                <%= label_tag(:period, "Срок:") %>
                <div id="slider"></div>
              </div>
              <br/>
              <br/>
            </div>
            <div class ="col-lg-6">
              <div class="panel panel-default" style="width:100%;">
                <div class="panel-body">
                  <em>Процентная ставка:</em>
                  <p style="font-size:200%">
                    <bold id="interest_rate"></bold>
                    <span>%</span>
                  </p>
                  <em>Ежемесячный %:</em><br>
                  <p style="font-size:200%">
                    <bold id="payment_summ">____</bold>
                    <span id="payment_summ_unit"></span>
                  </p>
                  <em>Общая сумма %:</em><br>
                  <p style="font-size:200%">
                    <bold id="payment_total_summ">____</bold>
                    <span id="payment_total_summ_unit"></span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-body">
    </div>
  </div>
<% end %>
<script type="text/javascript">
  var currcodes = []
                currcodes["417"] = 'KGS'
                currcodes["840"] = 'USD'
                currcodes["643"] = 'RUB'
                currcodes["978"] = 'EUR'
          var months = <%= GetDepositPeriods(@deposit["ProductID"]).to_s  %>
              $(document).ready(function () {
  
              $("#slider").slider({
                min: 0,
                max: <%= GetDepositPeriods(@deposit["ProductID"]).count-1 %>,
                range: false,
                change: calcVals
              })
  
              .slider("pips", {
                rest: "label",
                labels: months,
                suffix: " мес."
              })
              .slider('float');
  
              $("#txtdepositsum").on('change keyup paste input', calcVals);
              $('input[name="currency_id"]').on('change',calcVals);
              calcVals();
              });
              function calcVals()
              {
                var inters = []
                <% @deposit_interests.each do |inter|  %>
                  inters['<%="#{inter['CurrencyID']}_#{inter['MonthPeriod']}"%>']= <%=inter["InterestRate"]%>;
                <% end %>
  
  
                var currency_id = $('input[name="currency_id"]:checked').val();
                var periodindex = $( "#slider" ).slider( "value" );
                var period = months[periodindex];
                var rate = 0;
                if(inters[currency_id+'_'+period]) rate = inters[currency_id+'_'+period];
  
                var sum = 0;
                if ($("#txtdepositsum").val()!='') sum = parseInt($("#txtdepositsum").val())
  
                $("#interest_rate").html(rate);
                $("#payment_summ").html((sum*rate/1200.0).toFixed(2));
                $("#payment_summ_unit").html(currcodes[currency_id]);
                $("#payment_total_summ").html((period*sum*rate/1200.0).toFixed(2));
                $("#payment_total_summ_unit").html(currcodes[currency_id]);
              }
</script>