config/routes.rb
Rails.application.routes.draw do

  get 'management/index', as: "management"

  get 'special_offers/index', as: "special_offers"
  get 'special_offers/show/:id', to:"special_offers#show", as: "special_offer"
  get 'mini_special_offers/index', as: "mini_special_offers"
  get 'mini_special_offers/show/:id', to:"mini_special_offers#show", as: "mini_special_offer"

  namespace :admin do
    get 'deposit_types/show'
  end

  namespace :admin do
    get 'deposit_types/edit'
  end

  namespace :admin do
    get '/news', to:"news#index", as: "newsitems"
    get '/news/new', to:"news#new", as: "newsitem_new"
    post '/news', to:"news#create", as: "newsitem_create" 
    get '/news/:id', to:"news#show", as: "newsitem_show"
    get '/news/:id/edit', to:"news#edit", as: "newsitem_edit"
    patch '/news/:id', to:"news#update", as: "newsitem_update"
    delete '/news/:id', to:"news#delete", as: "newsitem_delete"
    
    post '/garants/add_image', to:"garants#add_image", as: "garant_images"
    post '/garants/add_detail', to:"garants#add_detail", as: "garant_details"
    post '/garants/destroy_image/:id/:image_id', to:"garants#destroy_image", as: "destroy_garant_image"
    post '/garants/destroy_detail/:id/:detail_id', to:"garants#destroy_detail", as: "destroy_garant_detail"
    resources :cash_terminals
    resources :garants
    resources :deposit_types
    resources :credit_types
    resources :credit_types
    resources :special_offers
    resources :mini_special_offers
    resources :offices
    resources :managers
    root "offices#index"

  end

  get 'garant/index', as: "garants"
  get 'garant/:garantid', to: "garant#show", as: "garant_show"

  get 'posterminals/index', as: "posterminals"

  get 'cards/index', as: "cards"

  get 'internetbank/index', as: "internetbank"

  get 'corraccounts/index', as: "corraccounts"

  get 'bankdetails/index', as: "bankdetails" 

  get 'report/index', as: "reports"

  get 'office/index', as: "offices"

  post 'office/show', as: "show_office_info"

  resources :users 
  
  post 'users/custom'

  namespace :products do
    namespace :credit_types do
      get 'credits(/:client_type(/:type_id))', to: "credits#index", defaults: {client_type: 1, type_id: 1}, as: "credits"
      get 'credits(/:client_type(/:type_id))/:product_id', to: "credits#show", defaults: {product_id: -1}, as: "creditdetails"
      post 'credits(/:client_type(/:type_id))/:product_id/calculate_rate_payment', to: "credits#calculate_rate_payment", defaults: {product_id: -1}, as: "calculate_rate_payment"
    end

    namespace :deposit_types do
      get 'deposits(/:client_type(/:type_id))', to: "deposits#index", defaults: {client_type: 1, type_id: 1}, as: "deposits"
      get 'deposits(/:client_type(/:type_id))/:product_id', to: "deposits#show", defaults: {product_id: -1}, as: "depositdetails"
      post 'deposits(/:client_type(/:type_id))/:product_id/calculate_rate_payment', to: "deposits#calculate_rate_payment", defaults: {product_id: -1}, as: "calculate_rate_payment"
    end

    namespace :transfer_types do 
      get '(:client_type)/international_transfers/', to: "international_transfers#index", defaults: {client_type: 1}, as: "international_transfers"
      get '(:client_type)/international_transfers/:typeid/', to: "international_transfers#show", defaults: {client_type: 1}, as: "international_transfer"
      post '(:client_type)/international_transfers/:typeid/commission_table', to: "international_transfers#commission_table", defaults: {client_type: 1}, as: "inter_commission_table"     
      post '(:client_type)/international_transfers/:typeid/calculate_commission_fee', to: "international_transfers#calculate_commission_fee", defaults: {client_type: 1}, as: "inter_calculate_commission_fee"  

      get '(:client_type)/local_transfers/', to: "local_transfers#index", defaults: {client_type: 1}, as: "local_transfers"

      get '(:client_type)/local_transfers/branch_transfers/', to: "local_transfers#show_branch_transfers", defaults: {client_type: 1}, as: "local_transfers_branch_transfers"
      post '(:client_type)/local_transfers/branch_transfers_commission_table', to: "local_transfers#branch_transfers_commission_table", defaults: {client_type: 1}, as: "branch_transfers_commission_table"     
      post '(:client_type)/local_transfers/branch_transfers_calculate_commission_fee', to: "local_transfers#branch_transfers_calculate_commission_fee", defaults: {client_type: 1}, as: "branch_transfers_calculate_commission_fee"  

      get '(:client_type)/local_transfers/cliring_gross/', to: "local_transfers#show_cliring_gross", defaults: {client_type: 1}, as: "local_transfers_cliring_gross"      
      post '(:client_type)/local_transfers/cliring_gross_calculate_commission_fee', to: "local_transfers#cliring_gross_calculate_commission_fee", defaults: {client_type: 1}, as: "cliring_gross_calculate_commission_fee"  

      get '(:client_type)/local_transfers/swift/', to: "local_transfers#show_swift", defaults: {client_type: 1}, as: "local_transfers_swift"
      post '(:client_type)/local_transfers/swift_calculate_commission_fee', to: "local_transfers#swift_calculate_commission_fee", defaults: {client_type: 1}, as: "swift_calculate_commission_fee"
    end

    get 'credit_types/(:client_type)', to: "credit_types#index", defaults: {client_type: 1}, as: "credit_purposes"
    get 'deposit_types/(:client_type)', to: "deposit_types#index", defaults: {client_type: 1}, as: "deposit_types"
    get 'transfer_types/(:client_type)', to: "transfer_types#index", defaults: {client_type: 1}, as: "transfer_types"
    get 'depository/(:client_type)', to: "depository#index", defaults: {client_type: 1}, as: "depository"

    post 'depository/(:client_type)/calculate_commission_fee', to: "depository#calculate_commission_fee", defaults: {client_type: 1}, as: "depository_calculate_commission_fee"
  end 


  get 'products/index'

  get 'credits(/:client_type(/:credit_type))', to: "credits#index", defaults: {client_type: 1, credit_type: 1}, as: "credits"

  get 'credits/show'

  get 'news/(:pageno)', to: "news#index", defaults: {pageno:1}, as: "news"
  get 'news/details/:id', to: "news#show", defaults: {:id=>1}, as: "news_details"


  get 'advice/index'

  get 'web_support/send_message'

  resources :rates

  root 'main#index'
  get 'main/index'

  resources :newsitems
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/views/shared/_credit_type.html.erb
<div class="col-sm-6 col-md-6">
  <div class="thumbnail">
    <%= image_tag(credit_type.image.url(:large), :style => "width: 100%;") %>
    <div class="caption">
      <h3 class="text-warning"><%= purpose["Name"] %></h3>
      <p class="card-description"><strong><%=credit_type.description %></strong>
        <strong><%=credit_type.footer %></strong></p>
      <p><%= link_to products_credit_types_credits_path(params["client_type"].to_i, purpose["ID"]), :title => "Узнать больше", :class=> "btn btn-danger btn-large" do %>
          <i class="icon-ok"></i> Узнать больше
                     <% end %></p>
    </div>
  </div>
</div>

app/views/shared/_deposit_type.html.erb
<div class="col-sm-6 col-md-6">
  <div class="thumbnail">
    <%= image_tag(details.image.url(:large), :style => "width: 100%;") %>
    <div class="caption">
      <h3 class="text-warning"><%= abs_deposit_type["Name"] %></h3>
      <p class="card-description"><strong><%=details.description %></strong>
        <strong><%=details.footer %></strong></p>
      <p><%= link_to products_deposit_types_deposits_path(params["client_type"].to_i, abs_deposit_type["TypeID"]), :title => "Узнать больше", :class=> "btn btn-danger btn-large" do %>
          <i class="icon-ok"></i> Узнать больше
                     <% end %></p>
    </div>
  </div>
</div>

app/views/shared/_fasttransfers.html.erb
<a href ='#'>
    <div class='ftrect' style='background-position: 0px 0px;'>
    </div>
  </a>
  <div class='ftrect' style='background-position: 0px -40px;'>
    <a href ='#'></a>
  </div>
  <div class='ftrect' style='background-position: 0px -80px;'>
    <a href ='#'></a>
  </div>
  <div class='ftrect' style='background-position: 0px -122px;'>
    <a href ='#'></a>
  </div>
  <div class='ftrect' style='background-position: 0px -162px;'>
    <a href ='#'></a>
  </div>
  <div class='ftrect' style='background-position: 0px -202px;'>
    <a href ='#'></a>
  </div>
  <div class='ftrect' style='background-position: 0px -242px;'>
    <a href ='#'></a>
  </div>
  <div class='ftrect' style='background-position: 0px -280px;'>
    <a href ='#'></a>
  </div>

app/views/shared/_garant.html.erb
<div class = 'container'>
  <div class = 'row'>
    <div class = 'col-xs-12 col-md-12'>
      <div class="page-header">
        <h2><%=garant.name%>&nbsp&nbsp&nbsp&nbsp<small style="color:#000;"><i class="fa fa-phone-square" aria-hidden="true" style="color:#d40000"></i> 0555-555555</small></h2>
      </div>
    </div>
  </div>
  <div class = "row">
    <div class = 'col-xs-12 col-md-12'>
      <table class="table table-hover">
        <tr>
          <th>Стоимость</th>
          <th style="color:red;"><%=garant.cost%> сом</th>
        </tr>
        <tr>
          <th>Общее описание</th>
          <td><%= garant.description%></td>
        </tr>
        <% garant.garant_details.each do |detail|%>
          <tr>
            <th><%=detail.prop_key%></th>
            <td><%=detail.prop_value%></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class = "row">
    <div class = 'col-xs-12 col-md-12'>
      <% garant.garant_images.each do |image|%>
        <div  style="float:left; margin-left:10px">
          <a href="#" data-toggle="modal" data-target=".pop-up-<%=image.id%>">
            <%= image_tag(image.image.url(:med), class: "img-responsive img-rounded center-block")%>
          </a>
        </div>
        <!--  Modal content for the mixer image example -->
        <div class="modal fade pop-up-<%=image.id%>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel-1" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myLargeModalLabel-1"><%=image.image_description%></h4>
              </div>
              <div class="modal-body">
                <%= image_tag(image.image.url(:large), class: "img-responsive img-rounded center-block")%>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
      <% end %>
      <!-- /.modal mixer image -->
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="page-header">
  <h2>
    <%=title%>
    <small><%=raw(subtitle)%></small>
  </h2>
</div>

app/views/shared/_mainmenu.html.erb
       
<div id='mainmenu'>
  <div style="position:relative">
    <span>
      <a style="position:absolute;top:0px;" class="menu-toggle" id = 'open-menu' href="#">
        <%= image_tag("hamburger.svg")%></a>
    </span>
    <span>
      <%= image_tag("logoShort.svg", :id=>"minibrand")%>
    </span>
    <ul class="nav navbar-nav" id="bs-example-navbar-collapse-1">
      <li class="dropdown menu-large">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                  <% if params["client_type"].to_i==2%> 
                  style="color:#d40000;text-decoration:underline"
                  <% end %>
                  >Корпоративным клиентам</a>
        <ul class="dropdown-menu megamenu row">
          <li class="col-sm-4">
            <ul>
              <li><a href="#" class="nav-child"><strong></strong></a></li>
              <li>
                <%= link_to products_deposit_types_path(2), :title => "Депозиты корпоративным клиентам", :class=> "nav-child" do %>
                  <strong>ДЕПОЗИТЫ</strong>
                <% end %>
              </li>
              <% DEPOSITS_PRODUCTS.select{|x| x["OrganizationTypeID"]==2 and x["ProductID"].in?([101,107,109,119,126])}.each do |purpose| %>
                <li><a href="#"><%= purpose["Name"]%></a></li>
              <% end %>
              <li><a href="#">...</a></li>
            </ul>
          </li>
          <li class="col-sm-4">
            <ul>
              <li>
                <%= link_to products_credit_purposes_path(2), :title => "Кредиты корпоративным клиентам", :class=> "nav-child" do %>
                  <strong>КРЕДИТЫ</strong>
                <% end %>
              </li>
              <% CREDITS_PURPOSES.select{|x| x["IsForCompanies"]}.each do |credit_purpose| %>
                <li>
                  <%= link_to credit_purpose["Name"], products_credit_types_credits_path(2,credit_purpose["ID"]) %>
                </li>
              <% end %>
              <li>
                <%= link_to(internetbank_path()) do %>
                  <strong>ИНТЕРНЕТ БАНКИНГ</strong>
                <% end %>
              </li>
              <li>
                <%= link_to cards_path() do %>
                  <strong>ЗАРПЛАТНЫЕ ПРОЕКТЫ</strong>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="col-sm-4">
            <ul>
              <li><%= link_to(products_depository_path(1)) do %>
                  <strong>СЕЙФОВЫЕ ЯЧЕЙКИ</strong>
                <% end %>
              </li>
              <li><a href="#" class="nav-child"><strong>ДЕНЕЖНЫЕ ПЕРЕВОДЫ</strong></a></li>
              <li><%= link_to "Переводы Клиринг/Гросс", products_transfer_types_local_transfers_cliring_gross_path(2) %></li>
              <li><%= link_to "Международные переводы СВИФТ", products_transfer_types_local_transfers_swift_path(2) %></li>
              <li><%= link_to "Межфилиальные переводы Салам", products_transfer_types_local_transfers_branch_transfers_path(2) %></li>
              <li><%= link_to(garants_path(1)) do %>
                  <strong>РЕАЛИЗАЦИЯ ЗАЛОГОВОГО ИМУЩЕСТВА</strong>
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </li>
      <li class="dropdown menu-large">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                <% if params["client_type"].to_i==1%> 
                  style="color:#d40000;text-decoration:underline"
                  <% end %>>Частным клиентам</a>
        <ul class="dropdown-menu megamenu row">
          <li class="col-sm-3">
            <ul>
              <li>
                <%= link_to products_deposit_types_path(1), :title => "Депозиты частным клиентам", :class=> "nav-child" do %>
                  <strong>ДЕПОЗИТЫ</strong>
                <% end %>
              </li>
              <% DEPOSITS_PRODUCTS.select{|x| x["OrganizationTypeID"]==1}.each do |purpose| %>
                <li><a href="#"><%= purpose["Name"]%></a></li>
              <% end %>
            </ul>
          </li>
          <li class="col-sm-3">
            <ul>
              <li>
                <%= link_to products_credit_purposes_path(1), :title => "Кредиты частным клиентам", :class=> "nav-child" do %>
                  <strong>КРЕДИТЫ</strong>
                <% end %>
              </li>
              <% CREDITS_PURPOSES.select{|x| x["IsForIndividuals"]}.each do |credit_purpose| %>
                <li>
                  <%= link_to credit_purpose["Name"], products_credit_types_credits_path(1,credit_purpose["ID"]) %>
                </li>
              <% end %>
              <li>
                <%= link_to internetbank_path() do %>
                  <strong>ИНТЕРНЕТ БАНКИНГ</strong>
                <% end %>
              </li>
              <li><%= link_to cards_path() do %>
                  <strong>ПЛАТЕЖНЫЕ КАРТЫ</strong>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="col-sm-3">
            <ul>
              <li><%= link_to(products_depository_path(1)) do %>
                  <strong>СЕЙФОВЫЕ ЯЧЕЙКИ</strong>
                <% end %>
              </li>
              <li><a href="#" class="nav-child"><strong>ДЕНЕЖНЫЕ ПЕРЕВОДЫ ВНУТРИ КР</strong></a></li>
              <li><%= link_to "Переводы Клиринг/Гросс", products_transfer_types_local_transfers_cliring_gross_path(1) %></li>
              <li><%= link_to "Межфилиальные переводы Салам", products_transfer_types_local_transfers_branch_transfers_path(1) %></li>
              <li><%= link_to(garants_path(1)) do %>
                  <strong>РЕАЛИЗАЦИЯ ЗАЛОГОВОГО ИМУЩЕСТВА</strong>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="col-sm-3">
            <ul>
              <li>
                <%= link_to products_transfer_types_international_transfers_path(1), :class => "nav-child" do %>
                  <strong>МЕЖДУНАРОДНЫЕ ПЕРЕВОДЫ</strong>
                <% end %>
              </li>
              <li>
                <%= link_to "Международные переводы СВИФТ", products_transfer_types_local_transfers_swift_path(1) %>
              </li>
              <li><a href="#">Золотая корона</a></li>
              <li><a href="#">Монейграм</a></li>
              <li><a href="#">Фастер</a></li>
              <li><a href="#">Контакт</a></li>
              <li><a href="#">Юнистрим</a></li>
              <li><a href="#">Экспрессмоней</a></li>
              <li><a href="#">Близко</a></li>
              <li><a href="#">Салам</a></li>
            </ul>
          </li>
        </ul>
      </li>
      <li class="dropdown menu-large">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">О нашем банке</a>
        <ul class="dropdown-menu megamenu row">
          <li class="col-sm-3">
            <ul>
              <li><a href="#" class="nav-child"><strong>О БАНКЕ</strong></a></li>
              <li><a href="#">Банк сегодня</a></li>
              <li><%= link_to("Руководство", management_path())%></li>
              <li><%= link_to("Филиалы и сберкассы", offices_path())%></li>
              <li><%= link_to("Банкоматы и постерминалы",posterminals_path())%></li>
              <li><%= link_to("Корреспондентская сеть",corraccounts_path())%></li>
            </ul>
          </li>
          <li class="col-sm-3">
            <ul>
              <li><a href="#" class="nav-child"><strong>ПРЕСС ЦЕНТР</strong></a></li>
              <li><%= link_to("Отчетность", reports_path(), class:"nav-child")%>  </li>
              <li><%= link_to("Новости", news_path())%></li>
              <li><a href="#">Акции</a></li>
              <li><a href="#">Фото галерея</a></li>
            </ul>
          </li>
          <li class="col-sm-6">
            <ul>
              <li><a href="#" class="nav-child"><strong>ОБЩАЯ ИНФОРМАЦИЯ</strong></a></li>
              <li><a href="#">Вакансии</a></li>
              <li><a href="#">Тендеры</a></li>
              <li><%= link_to("Реализация залогового имущества",garants_path())%></li>
              <li><%= link_to("Реквизиты",bankdetails_path())%></li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
    <span>
      <div id = "lang" class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" style="border:0px" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span style="color:#d40000;">Ru</span>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="width:50px;">
          <li><a href="#"><span class="flag flag-kg" style='width: 32px;display: block;float: left;margin-top:-5px;margin-left:-15px;'></span><span style="margin-left:4px;">Кыргызча</span></a></li>
          <li><a href="#"><span class="flag flag-ru" style='width: 32px;display: block;float: left;margin-top:-5px;margin-left:-15px;'></span><span style="margin-left:4px;">Русский</span></a></li>
          <li><a href="#"><span class="flag flag-gb" style='width: 32px;display: block;float: left;margin-top:-5px;margin-left:-15px;'></span><span style="margin-left:4px;">English</span></a></li>
        </ul>
      </div>
      <a id = 'search' href="#"><%= image_tag("search.svg") %></a>
    </span>
  </div>
</div>

app/views/shared/_manager.html.erb
<div class="avatar-flip">
  <%= image_tag manager.photo.url(:med)%>
</div>
<h3><%=manager.fullname%></h3>
<h4><%=manager.title%></h4>
<p><%=manager.biography%></p>
<p><%=manager.addresstoclients%></p>

app/views/shared/_mini_special_offer.html.erb
<%= image_tag(mini_special_offer.image.url(:large),style:"float:left;margin:10px 20px 10px 0px; box-shadow: 0 0 10px rgba(0,0,0,0.5);") %>

<p>  
  <%= mini_special_offer.creation_date %>
</p>
<p>
  <%= raw(mini_special_offer.body) %>
</p>

app/views/shared/_one_column_sidebar.html.erb
<%content_for :header do %>
	<%= render partial: "/shared/header", locals: {title: title, subtitle: subtitle} %>
<% end %>
<%content_for :breadcrumbs do %>
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ol>
<% end %>
<div class = 'col-xs-9 col-md-9'>
  <%= yield %>
</div>
<%content_for :sidebar do %>
  <div class = "col-xs-3 col-md-3" style="padding-right:0px;">
    <%= render partial: "/shared/small_banners", locals: {banners:@allminibanners}%>
    <%= render partial: "/shared/rates", locals: {market_rates_cash:@market_rates_cash,market_rates_noncash:@market_rates_noncash, currency_rates:@currency_rates, currencies: @currencies}%>
  </div>
<% end %>

app/views/shared/_show_newsitem.html.erb
<h2>
  <%= @newsitem.caption %></h2>
</p>
<p>  
  <i class="fa fa-calendar" aria-hidden="true"></i> <%= I18n.localize @newsitem.creation_date, format: :long %>
</p>
<p>
  <%= raw(@newsitem.body) %>
</p>

app/views/shared/_small_banner.html.erb
<div class = <%=class_name%>>
<% firstbanner = banners.first %>
<% banners.each do |minibanner| %>
  <div class = "banner _ac_ban <%= 'ac_ban' if minibanner==firstbanner%>">
    <%= link_to mini_special_offer_path(minibanner.id) do %>
      <%= image_tag(minibanner.image.url(:large)) %>
    <% end %>
    <span class="read_more">
      <%= link_to mini_special_offer_path(minibanner.id) do %>
        Подробнее <i class="fa fa-chevron-right" aria-hidden="true"></i>
      <% end %>
    </span>
  </div>
<% end %>
</div>
<script type="text/javascript">
      bg_changer = function(){
          oActive = $(".banners > .<%=class_name%> > .ac_ban");
  
       if (oActive.next().length > 0)
       {
         oActive.removeClass('ac_ban');
         oActive.next().addClass('ac_ban');
       }
       else
       {
         oActive.removeClass('ac_ban');
         oActive.parent().children().eq(0).addClass('ac_ban');
       }
     }
      $(function() {
        self.setInterval(bg_changer, <%= interval %>);
      });
</script>

app/views/shared/_small_banners.html.erb
<div class = 'banners'>
    <%= render partial: "/shared/small_banner", locals:{banners:banners.select{|x| x.priority==1},class_name:"first_bg",interval:6000}%>  
    <%= render partial: "/shared/small_banner", locals:{banners:banners.select{|x| x.priority!=1},class_name:"second_bg",interval:10000}%>
</div>
<script type="text/javascript">
  $(".banner").hover(function() {
        $(this).children('.read_more').fadeIn('normal');
        },function() {
        $(this).children('.read_more').fadeOut('normal');
        });
</script>

app/views/shared/_special_offer.html.erb
<%= image_tag(special_offer.image.url(:large)) %>
<h2>
  <%= special_offer.caption %></h2>
</p>
<p>  
  <%= special_offer.creation_date %>
</p>
<p>
  <%= raw(special_offer.body) %>
</p>

app/views/shared/_transfer_commissions.html.erb
<% @transfer_commissions.each do |commission| %>
  <tr>
    <td><%= commission.minsum %> - <%= commission.maxsum %> </td>
    <td><%= commission.commission %>
      <% if(commission.in_percent) %>
        %
        <% end %> 
    </td>
  </tr>
<% end %>